version: "3.9"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: research
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  backend:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://appuser:password@db:5432/research
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

volumes:
  db_data:
  redis_data:
